# SPDX-License-Identifier: Apache-2.0
"""Generated by tools/extract_bitmap.py -- do not edit by hand.

Maps every one of the 192 mini-MOSbius config-chain bits (`ctrl_out[191:0]`,
see SPEC.md Sec 2.1-2.2) to the `mosbius.sym` pin it drives, and for the 162
bits that close a switch, to the crosspoint/bus/row it closes.

Ground truth is `ttsky-mini-mosbius/src/project.v`, the RTL wiring that was
actually taped out -- see SPEC.md Sec 2.9 and the module docstring in
tools/extract_bitmap.py for why that supersedes the web configurator's SVG.

Regenerate with:
    python3 tools/extract_bitmap.py --write
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MatrixBit:
    """One of the 162 bits that close a `tt_asw_3v3` transmission gate.

    156 of these sit in the 26-column switch matrix (chain positions 0-155)
    and connect a crosspoint node (a device terminal) to one row of one bus
    side -- for those, `crosspoint`, `bus` and `row` are all set.

    6 more are `cfg_bus_short` (positions 0-5, the matrix's own column 0:
    joins `bus_A[row]` to `bus_B[row]`, no crosspoint, `bus=None`).

    The last 6 are `cfg_bus_pwr` (positions 168-174, living inside the
    diff-pair device-setting blocks per SPEC.md Sec 2.4/2.11 -- *not* part of
    the 26-column matrix). These tie one bus segment directly to a rail:
    `crosspoint=None`, `bus` set, `rail` set to "VAPWR" or "VGND".
    """

    bit: int          # position in ctrl_out[191:0] / the 192-bit chain
    pin: str           # mosbius.sym pin name, e.g. "cfga_nfeta_s"
    index: int         # 1-based index into that pin's [N:1] array
    crosspoint: str | None  # xpt_<signal> node; None for cfg_bus_short/cfg_bus_pwr
    bus: str | None    # "A", "B", or None (cfg_bus_short joins both sides)
    row: int           # bus row 1-6
    rail: str | None = None  # "VAPWR"/"VGND" for cfg_bus_pwr bits, else None


@dataclass(frozen=True)
class DeviceSettingBit:
    """One of the 30 remaining bits: device widths, mirror ratios, diff-pair/
    OTA tails, the 4 FET source ties, the 2 diff-pair source ties, and OTA
    mode (chain positions 156-191, minus the 6 cfg_bus_pwr bits above).
    """

    bit: int    # position in ctrl_out[191:0] / the 192-bit chain
    pin: str    # mosbius.sym pin name, e.g. "ctrl_pfeta_width"
    index: int  # 0-based bit position within that pin (0 for single-bit pins)



MATRIX_BITS: dict[int, MatrixBit] = {
    0: MatrixBit(bit=0, pin="cfg_bus_short", index=1, crosspoint=None, bus=None, row=1, rail=None),
    1: MatrixBit(bit=1, pin="cfg_bus_short", index=4, crosspoint=None, bus=None, row=4, rail=None),
    2: MatrixBit(bit=2, pin="cfg_bus_short", index=2, crosspoint=None, bus=None, row=2, rail=None),
    3: MatrixBit(bit=3, pin="cfg_bus_short", index=5, crosspoint=None, bus=None, row=5, rail=None),
    4: MatrixBit(bit=4, pin="cfg_bus_short", index=3, crosspoint=None, bus=None, row=3, rail=None),
    5: MatrixBit(bit=5, pin="cfg_bus_short", index=6, crosspoint=None, bus=None, row=6, rail=None),
    6: MatrixBit(bit=6, pin="cfga_otan_outp", index=1, crosspoint="xpt_otan_outp", bus="A", row=1, rail=None),
    7: MatrixBit(bit=7, pin="cfga_otan_outp", index=4, crosspoint="xpt_otan_outp", bus="A", row=4, rail=None),
    8: MatrixBit(bit=8, pin="cfga_otan_outp", index=2, crosspoint="xpt_otan_outp", bus="A", row=2, rail=None),
    9: MatrixBit(bit=9, pin="cfga_otan_outp", index=5, crosspoint="xpt_otan_outp", bus="A", row=5, rail=None),
    10: MatrixBit(bit=10, pin="cfga_otan_outp", index=3, crosspoint="xpt_otan_outp", bus="A", row=3, rail=None),
    11: MatrixBit(bit=11, pin="cfga_otan_outp", index=6, crosspoint="xpt_otan_outp", bus="A", row=6, rail=None),
    12: MatrixBit(bit=12, pin="cfgb_otan_outm", index=1, crosspoint="xpt_otan_outm", bus="B", row=1, rail=None),
    13: MatrixBit(bit=13, pin="cfgb_otan_outm", index=4, crosspoint="xpt_otan_outm", bus="B", row=4, rail=None),
    14: MatrixBit(bit=14, pin="cfgb_otan_outm", index=2, crosspoint="xpt_otan_outm", bus="B", row=2, rail=None),
    15: MatrixBit(bit=15, pin="cfgb_otan_outm", index=5, crosspoint="xpt_otan_outm", bus="B", row=5, rail=None),
    16: MatrixBit(bit=16, pin="cfgb_otan_outm", index=3, crosspoint="xpt_otan_outm", bus="B", row=3, rail=None),
    17: MatrixBit(bit=17, pin="cfgb_otan_outm", index=6, crosspoint="xpt_otan_outm", bus="B", row=6, rail=None),
    18: MatrixBit(bit=18, pin="cfga_otan_inp", index=1, crosspoint="xpt_otan_inp", bus="A", row=1, rail=None),
    19: MatrixBit(bit=19, pin="cfgb_otan_inm", index=1, crosspoint="xpt_otan_inm", bus="B", row=1, rail=None),
    20: MatrixBit(bit=20, pin="cfga_otan_inp", index=2, crosspoint="xpt_otan_inp", bus="A", row=2, rail=None),
    21: MatrixBit(bit=21, pin="cfgb_otan_inm", index=2, crosspoint="xpt_otan_inm", bus="B", row=2, rail=None),
    22: MatrixBit(bit=22, pin="cfga_otan_inp", index=3, crosspoint="xpt_otan_inp", bus="A", row=3, rail=None),
    23: MatrixBit(bit=23, pin="cfgb_otan_inm", index=3, crosspoint="xpt_otan_inm", bus="B", row=3, rail=None),
    24: MatrixBit(bit=24, pin="cfga_nfeta_s", index=1, crosspoint="xpt_nfeta_s", bus="A", row=1, rail=None),
    25: MatrixBit(bit=25, pin="cfga_nfeta_s", index=4, crosspoint="xpt_nfeta_s", bus="A", row=4, rail=None),
    26: MatrixBit(bit=26, pin="cfga_nfeta_s", index=2, crosspoint="xpt_nfeta_s", bus="A", row=2, rail=None),
    27: MatrixBit(bit=27, pin="cfga_nfeta_s", index=5, crosspoint="xpt_nfeta_s", bus="A", row=5, rail=None),
    28: MatrixBit(bit=28, pin="cfga_nfeta_s", index=3, crosspoint="xpt_nfeta_s", bus="A", row=3, rail=None),
    29: MatrixBit(bit=29, pin="cfga_nfeta_s", index=6, crosspoint="xpt_nfeta_s", bus="A", row=6, rail=None),
    30: MatrixBit(bit=30, pin="cfga_nfeta_d", index=1, crosspoint="xpt_nfeta_d", bus="A", row=1, rail=None),
    31: MatrixBit(bit=31, pin="cfga_nfeta_d", index=4, crosspoint="xpt_nfeta_d", bus="A", row=4, rail=None),
    32: MatrixBit(bit=32, pin="cfga_nfeta_d", index=2, crosspoint="xpt_nfeta_d", bus="A", row=2, rail=None),
    33: MatrixBit(bit=33, pin="cfga_nfeta_d", index=5, crosspoint="xpt_nfeta_d", bus="A", row=5, rail=None),
    34: MatrixBit(bit=34, pin="cfga_nfeta_d", index=3, crosspoint="xpt_nfeta_d", bus="A", row=3, rail=None),
    35: MatrixBit(bit=35, pin="cfga_nfeta_d", index=6, crosspoint="xpt_nfeta_d", bus="A", row=6, rail=None),
    36: MatrixBit(bit=36, pin="cfgb_nfetb_s", index=1, crosspoint="xpt_nfetb_s", bus="B", row=1, rail=None),
    37: MatrixBit(bit=37, pin="cfgb_nfetb_s", index=4, crosspoint="xpt_nfetb_s", bus="B", row=4, rail=None),
    38: MatrixBit(bit=38, pin="cfgb_nfetb_s", index=2, crosspoint="xpt_nfetb_s", bus="B", row=2, rail=None),
    39: MatrixBit(bit=39, pin="cfgb_nfetb_s", index=5, crosspoint="xpt_nfetb_s", bus="B", row=5, rail=None),
    40: MatrixBit(bit=40, pin="cfgb_nfetb_s", index=3, crosspoint="xpt_nfetb_s", bus="B", row=3, rail=None),
    41: MatrixBit(bit=41, pin="cfgb_nfetb_s", index=6, crosspoint="xpt_nfetb_s", bus="B", row=6, rail=None),
    42: MatrixBit(bit=42, pin="cfgb_nfetb_d", index=1, crosspoint="xpt_nfetb_d", bus="B", row=1, rail=None),
    43: MatrixBit(bit=43, pin="cfgb_nfetb_d", index=4, crosspoint="xpt_nfetb_d", bus="B", row=4, rail=None),
    44: MatrixBit(bit=44, pin="cfgb_nfetb_d", index=2, crosspoint="xpt_nfetb_d", bus="B", row=2, rail=None),
    45: MatrixBit(bit=45, pin="cfgb_nfetb_d", index=5, crosspoint="xpt_nfetb_d", bus="B", row=5, rail=None),
    46: MatrixBit(bit=46, pin="cfgb_nfetb_d", index=3, crosspoint="xpt_nfetb_d", bus="B", row=3, rail=None),
    47: MatrixBit(bit=47, pin="cfgb_nfetb_d", index=6, crosspoint="xpt_nfetb_d", bus="B", row=6, rail=None),
    48: MatrixBit(bit=48, pin="cfgb_nfetb_g", index=1, crosspoint="xpt_nfetb_g", bus="B", row=1, rail=None),
    49: MatrixBit(bit=49, pin="cfgb_nfetb_g", index=4, crosspoint="xpt_nfetb_g", bus="B", row=4, rail=None),
    50: MatrixBit(bit=50, pin="cfgb_nfetb_g", index=2, crosspoint="xpt_nfetb_g", bus="B", row=2, rail=None),
    51: MatrixBit(bit=51, pin="cfgb_nfetb_g", index=5, crosspoint="xpt_nfetb_g", bus="B", row=5, rail=None),
    52: MatrixBit(bit=52, pin="cfgb_nfetb_g", index=3, crosspoint="xpt_nfetb_g", bus="B", row=3, rail=None),
    53: MatrixBit(bit=53, pin="cfgb_nfetb_g", index=6, crosspoint="xpt_nfetb_g", bus="B", row=6, rail=None),
    54: MatrixBit(bit=54, pin="cfga_nfeta_g", index=1, crosspoint="xpt_nfeta_g", bus="A", row=1, rail=None),
    55: MatrixBit(bit=55, pin="cfga_nfeta_g", index=4, crosspoint="xpt_nfeta_g", bus="A", row=4, rail=None),
    56: MatrixBit(bit=56, pin="cfga_nfeta_g", index=2, crosspoint="xpt_nfeta_g", bus="A", row=2, rail=None),
    57: MatrixBit(bit=57, pin="cfga_nfeta_g", index=5, crosspoint="xpt_nfeta_g", bus="A", row=5, rail=None),
    58: MatrixBit(bit=58, pin="cfga_nfeta_g", index=3, crosspoint="xpt_nfeta_g", bus="A", row=3, rail=None),
    59: MatrixBit(bit=59, pin="cfga_nfeta_g", index=6, crosspoint="xpt_nfeta_g", bus="A", row=6, rail=None),
    60: MatrixBit(bit=60, pin="cfga_mirn_a", index=1, crosspoint="xpt_mirn_a", bus="A", row=1, rail=None),
    61: MatrixBit(bit=61, pin="cfga_mirn_a", index=4, crosspoint="xpt_mirn_a", bus="A", row=4, rail=None),
    62: MatrixBit(bit=62, pin="cfga_mirn_a", index=2, crosspoint="xpt_mirn_a", bus="A", row=2, rail=None),
    63: MatrixBit(bit=63, pin="cfga_mirn_a", index=5, crosspoint="xpt_mirn_a", bus="A", row=5, rail=None),
    64: MatrixBit(bit=64, pin="cfga_mirn_a", index=3, crosspoint="xpt_mirn_a", bus="A", row=3, rail=None),
    65: MatrixBit(bit=65, pin="cfga_mirn_a", index=6, crosspoint="xpt_mirn_a", bus="A", row=6, rail=None),
    66: MatrixBit(bit=66, pin="cfgb_mirn_b", index=1, crosspoint="xpt_mirn_b", bus="B", row=1, rail=None),
    67: MatrixBit(bit=67, pin="cfgb_mirn_b", index=4, crosspoint="xpt_mirn_b", bus="B", row=4, rail=None),
    68: MatrixBit(bit=68, pin="cfgb_mirn_b", index=2, crosspoint="xpt_mirn_b", bus="B", row=2, rail=None),
    69: MatrixBit(bit=69, pin="cfgb_mirn_b", index=5, crosspoint="xpt_mirn_b", bus="B", row=5, rail=None),
    70: MatrixBit(bit=70, pin="cfgb_mirn_b", index=3, crosspoint="xpt_mirn_b", bus="B", row=3, rail=None),
    71: MatrixBit(bit=71, pin="cfgb_mirn_b", index=6, crosspoint="xpt_mirn_b", bus="B", row=6, rail=None),
    72: MatrixBit(bit=72, pin="cfga_dpn_inp", index=1, crosspoint="xpt_dpn_inp", bus="A", row=1, rail=None),
    73: MatrixBit(bit=73, pin="cfgb_dpn_inm", index=1, crosspoint="xpt_dpn_inm", bus="B", row=1, rail=None),
    74: MatrixBit(bit=74, pin="cfga_dpn_inp", index=2, crosspoint="xpt_dpn_inp", bus="A", row=2, rail=None),
    75: MatrixBit(bit=75, pin="cfgb_dpn_inm", index=2, crosspoint="xpt_dpn_inm", bus="B", row=2, rail=None),
    76: MatrixBit(bit=76, pin="cfga_dpn_inp", index=3, crosspoint="xpt_dpn_inp", bus="A", row=3, rail=None),
    77: MatrixBit(bit=77, pin="cfgb_dpn_inm", index=3, crosspoint="xpt_dpn_inm", bus="B", row=3, rail=None),
    78: MatrixBit(bit=78, pin="cfga_dpn_outp", index=1, crosspoint="xpt_dpn_outp", bus="A", row=1, rail=None),
    79: MatrixBit(bit=79, pin="cfga_dpn_outp", index=4, crosspoint="xpt_dpn_outp", bus="A", row=4, rail=None),
    80: MatrixBit(bit=80, pin="cfga_dpn_outp", index=2, crosspoint="xpt_dpn_outp", bus="A", row=2, rail=None),
    81: MatrixBit(bit=81, pin="cfga_dpn_outp", index=5, crosspoint="xpt_dpn_outp", bus="A", row=5, rail=None),
    82: MatrixBit(bit=82, pin="cfga_dpn_outp", index=3, crosspoint="xpt_dpn_outp", bus="A", row=3, rail=None),
    83: MatrixBit(bit=83, pin="cfga_dpn_outp", index=6, crosspoint="xpt_dpn_outp", bus="A", row=6, rail=None),
    84: MatrixBit(bit=84, pin="cfgb_dpn_outm", index=1, crosspoint="xpt_dpn_outm", bus="B", row=1, rail=None),
    85: MatrixBit(bit=85, pin="cfgb_dpn_outm", index=4, crosspoint="xpt_dpn_outm", bus="B", row=4, rail=None),
    86: MatrixBit(bit=86, pin="cfgb_dpn_outm", index=2, crosspoint="xpt_dpn_outm", bus="B", row=2, rail=None),
    87: MatrixBit(bit=87, pin="cfgb_dpn_outm", index=5, crosspoint="xpt_dpn_outm", bus="B", row=5, rail=None),
    88: MatrixBit(bit=88, pin="cfgb_dpn_outm", index=3, crosspoint="xpt_dpn_outm", bus="B", row=3, rail=None),
    89: MatrixBit(bit=89, pin="cfgb_dpn_outm", index=6, crosspoint="xpt_dpn_outm", bus="B", row=6, rail=None),
    90: MatrixBit(bit=90, pin="cfga_dpp_inp", index=1, crosspoint="xpt_dpp_inp", bus="A", row=1, rail=None),
    91: MatrixBit(bit=91, pin="cfgb_dpp_inm", index=1, crosspoint="xpt_dpp_inm", bus="B", row=1, rail=None),
    92: MatrixBit(bit=92, pin="cfga_dpp_inp", index=2, crosspoint="xpt_dpp_inp", bus="A", row=2, rail=None),
    93: MatrixBit(bit=93, pin="cfgb_dpp_inm", index=2, crosspoint="xpt_dpp_inm", bus="B", row=2, rail=None),
    94: MatrixBit(bit=94, pin="cfga_dpp_inp", index=3, crosspoint="xpt_dpp_inp", bus="A", row=3, rail=None),
    95: MatrixBit(bit=95, pin="cfgb_dpp_inm", index=3, crosspoint="xpt_dpp_inm", bus="B", row=3, rail=None),
    96: MatrixBit(bit=96, pin="cfga_dpp_outp", index=1, crosspoint="xpt_dpp_outp", bus="A", row=1, rail=None),
    97: MatrixBit(bit=97, pin="cfga_dpp_outp", index=4, crosspoint="xpt_dpp_outp", bus="A", row=4, rail=None),
    98: MatrixBit(bit=98, pin="cfga_dpp_outp", index=2, crosspoint="xpt_dpp_outp", bus="A", row=2, rail=None),
    99: MatrixBit(bit=99, pin="cfga_dpp_outp", index=5, crosspoint="xpt_dpp_outp", bus="A", row=5, rail=None),
    100: MatrixBit(bit=100, pin="cfga_dpp_outp", index=3, crosspoint="xpt_dpp_outp", bus="A", row=3, rail=None),
    101: MatrixBit(bit=101, pin="cfga_dpp_outp", index=6, crosspoint="xpt_dpp_outp", bus="A", row=6, rail=None),
    102: MatrixBit(bit=102, pin="cfgb_dpp_outm", index=1, crosspoint="xpt_dpp_outm", bus="B", row=1, rail=None),
    103: MatrixBit(bit=103, pin="cfgb_dpp_outm", index=4, crosspoint="xpt_dpp_outm", bus="B", row=4, rail=None),
    104: MatrixBit(bit=104, pin="cfgb_dpp_outm", index=2, crosspoint="xpt_dpp_outm", bus="B", row=2, rail=None),
    105: MatrixBit(bit=105, pin="cfgb_dpp_outm", index=5, crosspoint="xpt_dpp_outm", bus="B", row=5, rail=None),
    106: MatrixBit(bit=106, pin="cfgb_dpp_outm", index=3, crosspoint="xpt_dpp_outm", bus="B", row=3, rail=None),
    107: MatrixBit(bit=107, pin="cfgb_dpp_outm", index=6, crosspoint="xpt_dpp_outm", bus="B", row=6, rail=None),
    108: MatrixBit(bit=108, pin="cfga_mirp_a", index=1, crosspoint="xpt_mirp_a", bus="A", row=1, rail=None),
    109: MatrixBit(bit=109, pin="cfga_mirp_a", index=4, crosspoint="xpt_mirp_a", bus="A", row=4, rail=None),
    110: MatrixBit(bit=110, pin="cfga_mirp_a", index=2, crosspoint="xpt_mirp_a", bus="A", row=2, rail=None),
    111: MatrixBit(bit=111, pin="cfga_mirp_a", index=5, crosspoint="xpt_mirp_a", bus="A", row=5, rail=None),
    112: MatrixBit(bit=112, pin="cfga_mirp_a", index=3, crosspoint="xpt_mirp_a", bus="A", row=3, rail=None),
    113: MatrixBit(bit=113, pin="cfga_mirp_a", index=6, crosspoint="xpt_mirp_a", bus="A", row=6, rail=None),
    114: MatrixBit(bit=114, pin="cfgb_mirp_b", index=1, crosspoint="xpt_mirp_b", bus="B", row=1, rail=None),
    115: MatrixBit(bit=115, pin="cfgb_mirp_b", index=4, crosspoint="xpt_mirp_b", bus="B", row=4, rail=None),
    116: MatrixBit(bit=116, pin="cfgb_mirp_b", index=2, crosspoint="xpt_mirp_b", bus="B", row=2, rail=None),
    117: MatrixBit(bit=117, pin="cfgb_mirp_b", index=5, crosspoint="xpt_mirp_b", bus="B", row=5, rail=None),
    118: MatrixBit(bit=118, pin="cfgb_mirp_b", index=3, crosspoint="xpt_mirp_b", bus="B", row=3, rail=None),
    119: MatrixBit(bit=119, pin="cfgb_mirp_b", index=6, crosspoint="xpt_mirp_b", bus="B", row=6, rail=None),
    120: MatrixBit(bit=120, pin="cfga_pfeta_g", index=1, crosspoint="xpt_pfeta_g", bus="A", row=1, rail=None),
    121: MatrixBit(bit=121, pin="cfga_pfeta_g", index=4, crosspoint="xpt_pfeta_g", bus="A", row=4, rail=None),
    122: MatrixBit(bit=122, pin="cfga_pfeta_g", index=2, crosspoint="xpt_pfeta_g", bus="A", row=2, rail=None),
    123: MatrixBit(bit=123, pin="cfga_pfeta_g", index=5, crosspoint="xpt_pfeta_g", bus="A", row=5, rail=None),
    124: MatrixBit(bit=124, pin="cfga_pfeta_g", index=3, crosspoint="xpt_pfeta_g", bus="A", row=3, rail=None),
    125: MatrixBit(bit=125, pin="cfga_pfeta_g", index=6, crosspoint="xpt_pfeta_g", bus="A", row=6, rail=None),
    126: MatrixBit(bit=126, pin="cfgb_pfetb_g", index=1, crosspoint="xpt_pfetb_g", bus="B", row=1, rail=None),
    127: MatrixBit(bit=127, pin="cfgb_pfetb_g", index=4, crosspoint="xpt_pfetb_g", bus="B", row=4, rail=None),
    128: MatrixBit(bit=128, pin="cfgb_pfetb_g", index=2, crosspoint="xpt_pfetb_g", bus="B", row=2, rail=None),
    129: MatrixBit(bit=129, pin="cfgb_pfetb_g", index=5, crosspoint="xpt_pfetb_g", bus="B", row=5, rail=None),
    130: MatrixBit(bit=130, pin="cfgb_pfetb_g", index=3, crosspoint="xpt_pfetb_g", bus="B", row=3, rail=None),
    131: MatrixBit(bit=131, pin="cfgb_pfetb_g", index=6, crosspoint="xpt_pfetb_g", bus="B", row=6, rail=None),
    132: MatrixBit(bit=132, pin="cfgb_pfetb_d", index=1, crosspoint="xpt_pfetb_d", bus="B", row=1, rail=None),
    133: MatrixBit(bit=133, pin="cfgb_pfetb_d", index=4, crosspoint="xpt_pfetb_d", bus="B", row=4, rail=None),
    134: MatrixBit(bit=134, pin="cfgb_pfetb_d", index=2, crosspoint="xpt_pfetb_d", bus="B", row=2, rail=None),
    135: MatrixBit(bit=135, pin="cfgb_pfetb_d", index=5, crosspoint="xpt_pfetb_d", bus="B", row=5, rail=None),
    136: MatrixBit(bit=136, pin="cfgb_pfetb_d", index=3, crosspoint="xpt_pfetb_d", bus="B", row=3, rail=None),
    137: MatrixBit(bit=137, pin="cfgb_pfetb_d", index=6, crosspoint="xpt_pfetb_d", bus="B", row=6, rail=None),
    138: MatrixBit(bit=138, pin="cfgb_pfetb_s", index=1, crosspoint="xpt_pfetb_s", bus="B", row=1, rail=None),
    139: MatrixBit(bit=139, pin="cfgb_pfetb_s", index=4, crosspoint="xpt_pfetb_s", bus="B", row=4, rail=None),
    140: MatrixBit(bit=140, pin="cfgb_pfetb_s", index=2, crosspoint="xpt_pfetb_s", bus="B", row=2, rail=None),
    141: MatrixBit(bit=141, pin="cfgb_pfetb_s", index=5, crosspoint="xpt_pfetb_s", bus="B", row=5, rail=None),
    142: MatrixBit(bit=142, pin="cfgb_pfetb_s", index=3, crosspoint="xpt_pfetb_s", bus="B", row=3, rail=None),
    143: MatrixBit(bit=143, pin="cfgb_pfetb_s", index=6, crosspoint="xpt_pfetb_s", bus="B", row=6, rail=None),
    144: MatrixBit(bit=144, pin="cfga_pfeta_d", index=1, crosspoint="xpt_pfeta_d", bus="A", row=1, rail=None),
    145: MatrixBit(bit=145, pin="cfga_pfeta_d", index=4, crosspoint="xpt_pfeta_d", bus="A", row=4, rail=None),
    146: MatrixBit(bit=146, pin="cfga_pfeta_d", index=2, crosspoint="xpt_pfeta_d", bus="A", row=2, rail=None),
    147: MatrixBit(bit=147, pin="cfga_pfeta_d", index=5, crosspoint="xpt_pfeta_d", bus="A", row=5, rail=None),
    148: MatrixBit(bit=148, pin="cfga_pfeta_d", index=3, crosspoint="xpt_pfeta_d", bus="A", row=3, rail=None),
    149: MatrixBit(bit=149, pin="cfga_pfeta_d", index=6, crosspoint="xpt_pfeta_d", bus="A", row=6, rail=None),
    150: MatrixBit(bit=150, pin="cfga_pfeta_s", index=1, crosspoint="xpt_pfeta_s", bus="A", row=1, rail=None),
    151: MatrixBit(bit=151, pin="cfga_pfeta_s", index=4, crosspoint="xpt_pfeta_s", bus="A", row=4, rail=None),
    152: MatrixBit(bit=152, pin="cfga_pfeta_s", index=2, crosspoint="xpt_pfeta_s", bus="A", row=2, rail=None),
    153: MatrixBit(bit=153, pin="cfga_pfeta_s", index=5, crosspoint="xpt_pfeta_s", bus="A", row=5, rail=None),
    154: MatrixBit(bit=154, pin="cfga_pfeta_s", index=3, crosspoint="xpt_pfeta_s", bus="A", row=3, rail=None),
    155: MatrixBit(bit=155, pin="cfga_pfeta_s", index=6, crosspoint="xpt_pfeta_s", bus="A", row=6, rail=None),
    168: MatrixBit(bit=168, pin="cfg_bus_pwr", index=4, crosspoint=None, bus="B", row=1, rail="VAPWR"),
    169: MatrixBit(bit=169, pin="cfg_bus_pwr", index=5, crosspoint=None, bus="A", row=4, rail="VAPWR"),
    170: MatrixBit(bit=170, pin="cfg_bus_pwr", index=6, crosspoint=None, bus="B", row=6, rail="VAPWR"),
    172: MatrixBit(bit=172, pin="cfg_bus_pwr", index=1, crosspoint=None, bus="A", row=2, rail="VGND"),
    173: MatrixBit(bit=173, pin="cfg_bus_pwr", index=2, crosspoint=None, bus="B", row=5, rail="VGND"),
    174: MatrixBit(bit=174, pin="cfg_bus_pwr", index=3, crosspoint=None, bus="A", row=6, rail="VGND"),
}

DEVICE_SETTING_BITS: dict[int, DeviceSettingBit] = {
    156: DeviceSettingBit(bit=156, pin="ctrl_pfeta_width", index=1),
    157: DeviceSettingBit(bit=157, pin="ctrl_pfeta_width", index=0),
    158: DeviceSettingBit(bit=158, pin="ctrl_pfeta_source", index=0),
    159: DeviceSettingBit(bit=159, pin="ctrl_pfetb_source", index=0),
    160: DeviceSettingBit(bit=160, pin="ctrl_pfetb_width", index=1),
    161: DeviceSettingBit(bit=161, pin="ctrl_pfetb_width", index=0),
    162: DeviceSettingBit(bit=162, pin="ctrl_dpp_tail", index=0),
    163: DeviceSettingBit(bit=163, pin="ctrl_dpp_tail", index=1),
    164: DeviceSettingBit(bit=164, pin="ctrl_mirp_b", index=0),
    165: DeviceSettingBit(bit=165, pin="ctrl_mirp_b", index=1),
    166: DeviceSettingBit(bit=166, pin="ctrl_mirp_a", index=0),
    167: DeviceSettingBit(bit=167, pin="ctrl_mirp_a", index=1),
    171: DeviceSettingBit(bit=171, pin="ctrl_dpp_source", index=0),
    175: DeviceSettingBit(bit=175, pin="ctrl_dpn_source", index=0),
    176: DeviceSettingBit(bit=176, pin="ctrl_mirn_b", index=0),
    177: DeviceSettingBit(bit=177, pin="ctrl_mirn_b", index=1),
    178: DeviceSettingBit(bit=178, pin="ctrl_mirn_a", index=0),
    179: DeviceSettingBit(bit=179, pin="ctrl_mirn_a", index=1),
    180: DeviceSettingBit(bit=180, pin="ctrl_dpn_tail", index=0),
    181: DeviceSettingBit(bit=181, pin="ctrl_dpn_tail", index=1),
    182: DeviceSettingBit(bit=182, pin="ctrl_otan_tail", index=0),
    183: DeviceSettingBit(bit=183, pin="ctrl_otan_tail", index=1),
    184: DeviceSettingBit(bit=184, pin="ctrl_nfetb_width", index=1),
    185: DeviceSettingBit(bit=185, pin="ctrl_nfetb_width", index=0),
    186: DeviceSettingBit(bit=186, pin="ctrl_nfetb_source", index=0),
    187: DeviceSettingBit(bit=187, pin="ctrl_nfeta_source", index=0),
    188: DeviceSettingBit(bit=188, pin="ctrl_nfeta_width", index=1),
    189: DeviceSettingBit(bit=189, pin="ctrl_nfeta_width", index=0),
    190: DeviceSettingBit(bit=190, pin="ctrl_otan_mode", index=0),
    191: DeviceSettingBit(bit=191, pin="ctrl_otan_mode", index=1),
}

# Convenience: every bit, matrix or setting, keyed 0..191.
ALL_BITS: dict[int, MatrixBit | DeviceSettingBit] = {**MATRIX_BITS, **DEVICE_SETTING_BITS}
