# SPDX-License-Identifier: Apache-2.0
"""Load a SwitchConfig onto the real chip (SPEC.md Sec 3.5, M4).

IMPORTANT -- unlike every other module in this package, this one has not
been run against real hardware. mosbius/bitmap.py through mosbius/route.py
were all cross-checked against the submodule, the netlist, or each other;
none of that is possible here without a demoboard plugged in, which this
environment doesn't have. What follows is built from the TinyTapeout
tt-micropython-firmware SDK's actual source (read directly from
https://github.com/TinyTapeout/tt-micropython-firmware -- demoboard.py,
pins/analog_current_source.py, pins/manual_clock.py -- not guessed), but
it needs real bring-up before anyone trusts it. Sec 8.4's exit criterion
("--verify readback matches at least once during bring-up") exists
exactly to catch what can only be caught this way.

Architecture: the actual bit-shifting happens ON the RP2040, not by
round-tripping each of 192 bits over USB serial from the host -- that
would be both slow and awkward, since clock_project_once()/ui_in.value
are calls into the on-device ttboard SDK. Instead, generate_device_script()
builds a small MicroPython program parameterized with the bitstream, and
`mpremote run` (the SDK's own supported tool) executes it on the board
and streams back a single result line this module parses.

Safety-critical ordering, per SPEC.md Sec 3.5 -- get this right or a
supply short is 3 bits away (Sec 3.1's E1): `enable` (ui_in[1]) is held
LOW for the entire 192-bit shift and only raised once, after the last
bit. There is no code path here that raises it early.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path

from mosbius.check import SafetyReport, check
from mosbius.model import SwitchConfig

# AnalogCurrentSource.level is documented upstream as "0 - 0xffff, ...
# up to ~250 uA" -- approximate, not a calibrated figure. Treat this
# conversion as a starting point to calibrate against a real meter
# during bring-up, not as exact.
_APPROX_MAX_IBIAS_AMPS = 250e-6
_IBIAS_LEVEL_MAX = 0xFFFF


class ProgramError(Exception):
    """Programming was refused or failed, explained in SPEC.md Sec 1.1 terms."""


def _ibias_level(amps: float) -> int:
    level = round(amps / _APPROX_MAX_IBIAS_AMPS * _IBIAS_LEVEL_MAX)
    return max(0, min(_IBIAS_LEVEL_MAX, level))


def generate_device_script(
    config: SwitchConfig, *, project: str, reset: bool = True, verify: bool = False,
) -> str:
    """Build the MicroPython program that runs on the RP2040: select the
    project, set ibias, shift `config`'s 192 bits MSB-first with enable
    held low throughout, then raise enable. Prints one JSON result line.
    """
    bit_string = "".join("1" if bit in config.bits else "0" for bit in range(191, -1, -1))
    ibias_level = _ibias_level(config.ibias)

    return f'''\
# Generated by mosbius/program.py -- runs on the RP2040 via `mpremote run`.
import json
from ttboard.demoboard import DemoBoard
from ttboard.mode import RPMode

BITS = "{bit_string}"  # MSB first: BITS[0] is bit 191, BITS[191] is bit 0
PROJECT = {project!r}
DO_RESET = {reset!r}
DO_VERIFY = {verify!r}
IBIAS_LEVEL = {ibias_level!r}

result = {{"ok": False, "error": None, "verify_ok": None}}
try:
    # DemoBoard.get() takes no arguments (it's a bare singleton accessor --
    # mode comes from config.ini on creation); set the mode explicitly
    # afterward via its property setter instead of assuming config.ini
    # already has it right.
    tt = DemoBoard.get()
    tt.mode = RPMode.ASIC_RP_CONTROL

    if not tt.shuttle.has(PROJECT):
        raise RuntimeError("project %s not found on this shuttle" % PROJECT)
    tt.shuttle.get(PROJECT).enable()

    if tt.analog_current_source is not None:
        tt.analog_current_source.level = IBIAS_LEVEL
        tt.analog_current_source.enabled = True
    else:
        result["error"] = (
            "no analog_current_source on this board revision -- ibias not set "
            "by software; bias it externally per SPEC.md Sec 3.4b"
        )

    # -- Sec 3.5 step 1: enable low BEFORE anything else, for the whole shift.
    tt.ui_in[1] = 0

    # -- Sec 3.5 step 2: known state.
    if DO_RESET:
        tt.reset_project(True)
        tt.clock_project_once()
        tt.reset_project(False)

    # -- Sec 3.5 step 3: shift 192 bits, MSB first. enable stays low.
    for bit_char in BITS:
        tt.ui_in[0] = 1 if bit_char == "1" else 0
        tt.clock_project_once()

    # -- Sec 3.5 step 4: whole configuration applies at once.
    tt.ui_in[1] = 1

    if DO_VERIFY:
        # Sec 3.5's --verify: shift the same 192 bits again, sampling
        # data_out (uo_out[0]) BEFORE each clock -- the chain is 192 deep,
        # so what comes out now is what went in during the pass above.
        tt.ui_in[1] = 0
        captured = []
        for bit_char in BITS:
            captured.append(tt.uo_out[0])
            tt.ui_in[0] = 1 if bit_char == "1" else 0
            tt.clock_project_once()
        tt.ui_in[1] = 1
        captured_str = "".join("1" if b else "0" for b in captured)
        result["verify_ok"] = (captured_str == BITS)
        result["captured"] = captured_str

    result["ok"] = True
except Exception as e:
    result["error"] = str(e)

print("MOSBIUS_RESULT:" + json.dumps(result))
'''


def _run_mpremote(script: str, *, port: str | None) -> dict:
    if shutil.which("mpremote") is None:
        raise ProgramError(
            "CAN'T PROGRAM -- mpremote isn't installed\n\n"
            "  program.py drives the demoboard through mpremote, the official\n"
            "  MicroPython tool. Install it with 'pip install mpremote' and try\n"
            "  again."
        )
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as f:
        f.write(script)
        script_path = f.name

    cmd = ["mpremote"]
    if port:
        cmd += ["connect", port]
    cmd += ["run", script_path]

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    finally:
        Path(script_path).unlink(missing_ok=True)

    result_line = next(
        (line for line in proc.stdout.splitlines() if line.startswith("MOSBIUS_RESULT:")), None,
    )
    if result_line is None:
        raise ProgramError(
            f"CAN'T PROGRAM -- no result from the board\n\n"
            f"  mpremote exited with code {proc.returncode} and didn't print a "
            f"result line.\n"
            f"  This usually means the board isn't connected, is running the "
            f"wrong\n  firmware, or crashed before finishing. Raw output:\n\n"
            f"{proc.stdout}\n{proc.stderr}"
        )
    return json.loads(result_line[len("MOSBIUS_RESULT:"):])


def program(
    config: SwitchConfig,
    *,
    project: str = "tt_um_tnt_mosbius",
    force: bool = False,
    reset: bool = True,
    verify: bool = False,
    port: str | None = None,
    report: SafetyReport | None = None,
) -> dict:
    """Load `config` onto the chip. Refuses (unless force=True) if
    check() finds an ERROR -- SPEC.md Sec 3.1: the mandatory pre-upload
    gate. Returns the device's result dict; raises ProgramError on any
    failure (refused, unreachable board, or a failed --verify readback).
    """
    if report is None:
        report = check(config)

    if report.has_errors and not force:
        paths = "\n\n".join(f.message for f in report.errors)
        raise ProgramError(
            f"UPLOAD BLOCKED -- {len(report.errors)} safety error"
            f"{'s' if len(report.errors) != 1 else ''} found\n\n"
            f"{paths}\n\n"
            f"  Fix the design above, or re-run with force=True if you're "
            f"certain\n  this is safe (SPEC.md Sec 3.1) -- there is no other "
            f"way past this gate."
        )

    script = generate_device_script(config, project=project, reset=reset, verify=verify)
    result = _run_mpremote(script, port=port)

    if not result["ok"]:
        raise ProgramError(f"CAN'T PROGRAM -- {result['error']}")
    if verify and result.get("verify_ok") is False:
        raise ProgramError(
            f"VERIFY FAILED -- readback doesn't match what was sent\n\n"
            f"  sent:      {config.to_bitstream()}\n"
            f"  captured:  {result.get('captured', '?')}\n\n"
            f"  The chain may have lost sync mid-shift (a bad connection, "
            f"clock too\n  fast, or a level issue). Try a slower clock or "
            f"re-seating the board."
        )
    return result
