# SPDX-License-Identifier: Apache-2.0
"""Load a SwitchConfig onto the real chip (SPEC.md Sec 3.5, M4).

This module has run against real hardware: a TTDBv3 [3.2] demoboard with a
ttsky25a chip, 2026-08-28, where `--verify` read back exactly what was sent
-- SPEC.md Sec 8.4's exit criterion. The SDK calls it makes come from the
TinyTapeout tt-micropython-firmware source (demoboard.py,
pins/analog_current_source.py, pins/manual_clock.py), and the attributes it
reads off a board are noted with the date they were read.

Architecture: the actual bit-shifting happens ON the RP2040, not by
round-tripping each of 192 bits over USB serial from the host -- that
would be both slow and awkward, since clock_project_once()/ui_in.value
are calls into the on-device ttboard SDK. Instead, generate_device_script()
builds a small MicroPython program parameterized with the bitstream, and
`mpremote run` (the SDK's own supported tool) executes it on the board
and streams back a single result line this module parses.

Safety-critical ordering, per SPEC.md Sec 3.5 -- get this right or a
supply short is 3 bits away (Sec 3.1's E1): `enable` (ui_in[1]) is held
LOW for the entire 192-bit shift and only raised once, after the last
bit. There is no code path here that raises it early.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path

from mosbius.check import SafetyReport, check
from mosbius.model import SwitchConfig
from mosbius.pads import DEFAULT_PROJECT

# AnalogCurrentSource.level is documented upstream as "0 - 0xffff, ...
# up to ~250 uA" -- approximate, not a calibrated figure. Treat this
# conversion as a starting point to calibrate against a real meter
# during bring-up, not as exact.
_APPROX_MAX_IBIAS_AMPS = 250e-6
_IBIAS_LEVEL_MAX = 0xFFFF


class ProgramError(Exception):
    """Programming was refused or failed, explained in SPEC.md Sec 1.1 terms."""


# Device-side: read what chip is actually in the socket. Pasted into every
# generated script rather than duplicated, so `program` and `pads` cannot
# disagree about where the shuttle name comes from.
#
# The chip carries its own ROM and ttboard reads it at boot; tt.chip_ROM
# exposes .shuttle ('ttsky25a'), .repo ('TinyTapeout/tinytapeout-sky-25a')
# and .commit -- all three read off a real part 2026-08-29. tt.shuttle.run
# carries the same shuttle string by another route and is the fallback.
# Everything is getattr-guarded: an identity we could not read is worth a
# note, never a failed upload.
_IDENTITY_SNIPPET = """
def _read_identity(tt):
    found = {}
    rom = getattr(tt, 'chip_ROM', None)
    for key in ('shuttle', 'repo', 'commit'):
        value = getattr(rom, key, None)
        if isinstance(value, str) and value:
            found[key] = value
    if 'shuttle' not in found:
        value = getattr(tt.shuttle, 'run', None)
        if isinstance(value, str) and value:
            found['shuttle'] = value
    found['identity_source'] = 'chip ROM' if rom is not None else 'shuttle index'
    return found
"""


def _ibias_level(amps: float) -> int:
    level = round(amps / _APPROX_MAX_IBIAS_AMPS * _IBIAS_LEVEL_MAX)
    return max(0, min(_IBIAS_LEVEL_MAX, level))


def generate_device_script(
    config: SwitchConfig, *, project: str, reset: bool = True, verify: bool = False,
) -> str:
    """Build the MicroPython program that runs on the RP2040: select the
    project, set ibias, shift `config`'s 192 bits MSB-first with enable
    held low throughout, then raise enable. Prints one JSON result line.
    """
    bit_string = "".join("1" if bit in config.bits else "0" for bit in range(191, -1, -1))
    ibias_level = _ibias_level(config.ibias)

    return f'''\
# Generated by mosbius/program.py -- runs on the RP2040 via `mpremote run`.
import json

# Re-run the carrier detection BEFORE anything imports (and so creates) the
# DemoBoard singleton. `mpremote` soft-resets the board to get a clean REPL,
# and a soft reset does not reset the RP2350's GPIO: the pins are still
# driven from whatever ran last, so the boot-time "is a chip carrier
# plugged in?" test reads them back wrong, reports "No carrier present,
# skipping chiprom", and leaves the shuttle as `unknown` -- whose index
# contains no projects, so `tt.shuttle.has('tt_um_tnt_mosbius')` is False
# even with the chip sitting right there. Probing again from a known state
# fixes it. Verified on a TTDBv3 [3.2] demoboard, 2026-08-28.
from ttboard.boot.demoboard_detect import DemoboardDetect
DemoboardDetect.probe()

from ttboard.demoboard import DemoBoard
from ttboard.mode import RPMode
{_IDENTITY_SNIPPET}
BITS = "{bit_string}"  # MSB first: BITS[0] is bit 191, BITS[191] is bit 0
PROJECT = {project!r}
DO_RESET = {reset!r}
DO_VERIFY = {verify!r}
IBIAS_LEVEL = {ibias_level!r}

result = {{"ok": False, "error": None, "verify_ok": None, "ibias_set": None,
          "enabled_design": None}}
try:
    # DemoBoard.get() takes no arguments (it's a bare singleton accessor --
    # mode comes from config.ini on creation); set the mode explicitly
    # afterward via its property setter instead of assuming config.ini
    # already has it right.
    tt = DemoBoard.get()
    tt.mode = RPMode.ASIC_RP_CONTROL

    if not tt.shuttle.has(PROJECT):
        raise RuntimeError("project %s not found on this shuttle" % PROJECT)
    tt.shuttle.get(PROJECT).enable()

    # enable() raising nothing is not proof the mux selection stuck. Every
    # board boots into tt_um_factory_test, auto-clocked at 10 Hz (an LED
    # counting on the board is that test running, not this design) -- caught
    # on a real bench 2026-09-01, where enable() returned cleanly but the
    # board stayed on the factory test. tt.shuttle.enabled is the board's own
    # answer to what is actually selected, read back so the host can tell.
    result["enabled_design"] = str(tt.shuttle.enabled)

    # Whether the bias current was actually delivered is reported in its own
    # field, not in result["error"]. It used to be the latter, which meant it
    # was written and then discarded: the host only reads "error" when "ok"
    # is False, and "ok" goes True a few lines below on exactly this path. So
    # a board with no bias circuit reported a clean upload and a pad table
    # asserting a current nothing had supplied.
    if tt.analog_current_source is not None:
        tt.analog_current_source.level = IBIAS_LEVEL
        tt.analog_current_source.enabled = True
        result["ibias_set"] = True
    else:
        result["ibias_set"] = False

    # -- Sec 3.5 step 1: enable low BEFORE anything else, for the whole shift.
    tt.ui_in[1] = 0

    # -- Sec 3.5 step 2: known state.
    if DO_RESET:
        tt.reset_project(True)
        tt.clock_project_once()
        tt.reset_project(False)

    # -- Sec 3.5 step 3: shift 192 bits, MSB first. enable stays low.
    for bit_char in BITS:
        tt.ui_in[0] = 1 if bit_char == "1" else 0
        tt.clock_project_once()

    # -- Sec 3.5 step 4: whole configuration applies at once.
    tt.ui_in[1] = 1

    if DO_VERIFY:
        # Sec 3.5's --verify: shift the same 192 bits again, sampling
        # data_out (uo_out[0]) BEFORE each clock -- the chain is 192 deep,
        # so what comes out now is what went in during the pass above.
        tt.ui_in[1] = 0
        captured = []
        for bit_char in BITS:
            captured.append(tt.uo_out[0])
            tt.ui_in[0] = 1 if bit_char == "1" else 0
            tt.clock_project_once()
        tt.ui_in[1] = 1
        captured_str = "".join("1" if b else "0" for b in captured)
        result["verify_ok"] = (captured_str == BITS)
        result["captured"] = captured_str

    # Which pad each ua[k] comes out on depends on where this project sits
    # on the shuttle, so read the shuttle off the chip in the socket rather
    # than assuming it host-side. The chip carries its own ROM, and ttboard
    # exposes it as tt.chip_ROM -- .shuttle, .repo and .commit, all verified
    # against a ttsky25a part 2026-08-29. tt.shuttle.run is the same string
    # by another route, kept as a fallback for firmware that predates
    # chip_ROM. Guarded on its own so a renamed attribute cannot turn a
    # working upload into a failure.
    result.update(_read_identity(tt))

    result["ok"] = True
except Exception as e:
    result["error"] = str(e)

print("MOSBIUS_RESULT:" + json.dumps(result))
'''


def _run_mpremote(script: str, *, port: str | None, what: str = "CAN'T PROGRAM") -> dict:
    """Run one generated script on the board. `what` heads any failure, so
    a read-only identity lookup doesn't report itself as a failed upload.
    """
    if shutil.which("mpremote") is None:
        raise ProgramError(
            f"{what} -- mpremote isn't installed\n\n"
            "  program.py drives the demoboard through mpremote, the official\n"
            "  MicroPython tool. Install it with 'pip install mpremote' and try\n"
            "  again."
        )
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as f:
        f.write(script)
        script_path = f.name

    cmd = ["mpremote"]
    if port:
        cmd += ["connect", port]
    cmd += ["run", script_path]

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    finally:
        Path(script_path).unlink(missing_ok=True)

    result_line = next(
        (line for line in proc.stdout.splitlines() if line.startswith("MOSBIUS_RESULT:")), None,
    )
    if result_line is None:
        port_hint = (
            "  mpremote autodetects the port by default, and picks the wrong\n"
            "  serial device when more than one is plugged in (or the wrong one\n"
            "  claims the port first). Tell it which one is the demoboard with\n"
            "  --port, e.g. --port /dev/ttyACM0, and try again.\n\n"
            if port is None else
            f"  --port {port} was given explicitly, so this isn't mpremote picking\n"
            f"  the wrong device -- check the board is powered, plugged in, and\n"
            f"  actually enumerating at that path.\n\n"
        )
        raise ProgramError(
            f"{what} -- no result from the board\n\n"
            f"  mpremote exited with code {proc.returncode} and didn't print a "
            f"result line.\n"
            f"  This usually means the board isn't connected, is running the "
            f"wrong\n  firmware, or crashed before finishing.\n\n"
            f"{port_hint}"
            f"Raw output:\n\n"
            f"{proc.stdout}\n{proc.stderr}"
        )
    return json.loads(result_line[len("MOSBIUS_RESULT:"):])


def generate_identity_script(project: str | None = None) -> str:
    """The read-only counterpart of generate_device_script(): ask the board
    what chip is in the socket, and change nothing.

    Nothing here enables a project, touches `enable`, or clocks the chip --
    it reads the ROM the demoboard already parsed at boot. `project`, if
    given, is only looked up in the shuttle index so the caller can say
    "that macro isn't on this chip" instead of printing a pad table for a
    design that was never taped out on it.
    """
    return f'''\
# Generated by mosbius/program.py -- read-only board identity, no config change.
import json

# Same reason as the programming script: mpremote's soft reset leaves the
# RP2350's GPIO driven, so the boot-time carrier detection can conclude
# there is no chip and leave the shuttle as `unknown`. Probe again from a
# known state BEFORE anything creates the DemoBoard singleton.
from ttboard.boot.demoboard_detect import DemoboardDetect
DemoboardDetect.probe()

from ttboard.demoboard import DemoBoard
{_IDENTITY_SNIPPET}
PROJECT = {project!r}

result = {{"ok": False, "error": None}}
try:
    tt = DemoBoard.get()
    result.update(_read_identity(tt))
    if PROJECT is not None:
        result["has_project"] = bool(tt.shuttle.has(PROJECT))
    result["ok"] = True
except Exception as e:
    result["error"] = str(e)

print("MOSBIUS_RESULT:" + json.dumps(result))
'''


def read_board_identity(*, project: str | None = None, port: str | None = None) -> dict:
    """Which chip is in the socket, read from its own ROM.

    Returns at least {'shuttle': ...}; usually 'repo' and 'commit' too, and
    'has_project' when `project` was given. Raises ProgramError if the board
    can't be reached -- callers that only want the pad table should catch
    that and fall back, since a pad lookup is not worth failing over.
    """
    result = _run_mpremote(
        generate_identity_script(project), port=port, what="CAN'T READ THE BOARD",
    )
    if not result.get("ok"):
        raise ProgramError(f"CAN'T READ THE BOARD -- {result.get('error')}")
    if not result.get("shuttle"):
        raise ProgramError(
            "CAN'T READ THE BOARD -- it answered, but reported no shuttle\n\n"
            "  The demoboard reads the shuttle from the chip carrier's own ROM\n"
            "  at boot. Getting nothing back usually means no carrier is seated,\n"
            "  or the firmware is older than chip ROM support. Pass --shuttle\n"
            "  yourself to carry on regardless."
        )
    return result


def ibias_warning(result: dict, config: SwitchConfig) -> str | None:
    """What to say when the board could not deliver the bias current.

    Only the newer ETR demoboards carry the RP2350-controlled circuit that
    makes this current; on an older one `tt.analog_current_source` is None
    and the bias pin is simply unfed. The upload is still perfectly good --
    the 192 bits are on the chip -- but every mirror, differential-pair tail
    and OTA tail in the design is referenced to a current that isn't there,
    so a design using any of them measures nothing, quietly.
    """
    if result.get("ibias_set") is not False or not config.ibias:
        return None
    return (
        "\n  BIAS CURRENT NOT SET -- this demoboard has no current source.\n\n"
        f"  The bitstream is on the chip and correct. But {config.ibias * 1e6:.1f} uA was\n"
        "  asked for, and this board revision has no `analog_current_source`:\n"
        "  the RP2350-controlled bias circuit arrived on later ETR demoboards.\n"
        "  So the chip's bias pin is floating, and anything in this design that\n"
        "  mirrors it -- mosbius_nsink, mosbius_psource, mosbius_ntail,\n"
        "  mosbius_ptail, mosbius_ota -- has no operating point.\n\n"
        "  Feed it externally instead (SPEC.md Sec 3.4b): a bench supply through a\n"
        "  series resistor into the bias pad, sized so most of the supply is\n"
        "  dropped across the resistor. To confirm the pad and set the current:\n\n"
        "    python3 tools/ad3/measure_ibias_clamp_ad3.py --resistor 20000\n\n"
        "  A design of plain mosbius_nmos/mosbius_pmos FETs needs none of this."
    )


def program(
    config: SwitchConfig,
    *,
    project: str = DEFAULT_PROJECT,
    force: bool = False,
    reset: bool = True,
    verify: bool = False,
    port: str | None = None,
    report: SafetyReport | None = None,
) -> dict:
    """Load `config` onto the chip. Refuses (unless force=True) if
    check() finds an ERROR -- SPEC.md Sec 3.1: the mandatory pre-upload
    gate. Returns the device's result dict; raises ProgramError on any
    failure (refused, unreachable board, or a failed --verify readback).
    """
    if report is None:
        report = check(config)

    if report.has_errors and not force:
        paths = "\n\n".join(f.message for f in report.errors)
        raise ProgramError(
            f"UPLOAD BLOCKED -- {len(report.errors)} safety error"
            f"{'s' if len(report.errors) != 1 else ''} found\n\n"
            f"{paths}\n\n"
            f"  Fix the design above, or re-run with force=True if you're "
            f"certain\n  this is safe (SPEC.md Sec 3.1) -- there is no other "
            f"way past this gate."
        )

    script = generate_device_script(config, project=project, reset=reset, verify=verify)
    result = _run_mpremote(script, port=port)

    if not result["ok"]:
        raise ProgramError(f"CAN'T PROGRAM -- {result['error']}")
    enabled = result.get("enabled_design")
    if enabled is not None and project not in enabled:
        raise ProgramError(
            f"UPLOAD DIDN'T STICK -- the board says '{enabled}' is selected, "
            f"not {project!r}.\n\n"
            "  tt.shuttle.get(...).enable() ran with no error, but the chip's "
            "mux\n  selection did not end up on this project. Every board "
            "boots into\n  tt_um_factory_test, auto-clocked at 10 Hz -- an LED "
            "counting on the\n  board is that test running, not this design -- "
            "and enable() is what\n  is supposed to stop it and switch over; "
            "this time it did not. The\n  192 bits went somewhere, but not to "
            "a chip that is actually addressed\n  as this project. Re-run; if "
            "it keeps happening, check the board is\n  fully seated and try a "
            "fresh USB connection."
        )
    if verify and result.get("verify_ok") is False:
        raise ProgramError(
            f"VERIFY FAILED -- readback doesn't match what was sent\n\n"
            f"  sent:      {config.to_bitstream()}\n"
            f"  captured:  {result.get('captured', '?')}\n\n"
            f"  The chain may have lost sync mid-shift (a bad connection, "
            f"clock too\n  fast, or a level issue). Try a slower clock or "
            f"re-seating the board."
        )
    return result
