# SPDX-License-Identifier: Apache-2.0
"""Emit an ngspice include that drives every `mosbius.sym` config pin
directly, per SPEC.md Sec 3.7.

Because `mosbius.sym` already exposes all 192 config bits as named digital
input pins, simulating a SwitchConfig needs no behavioural model of the
shift register at all -- each bit becomes a short-circuit tie from its pin
net to either VGND (bit clear) or VDPWR (bit set). Ties, not independent
voltage sources, so every config pin rides on the testbench's own
VDPWR/VGND supply nets rather than a second, possibly-mismatched copy of
them.

This is also SPEC.md Sec 3.8's "SPICE subckt" decode output form: the
identical include drives a bitstream decoded from anywhere, not just one
produced by the (not-yet-built) router.
"""

from __future__ import annotations

from mosbius.chips import DEFAULT_CHIP, Chip
from mosbius.model import SwitchConfig

# mosbius.sym pins declared without a [N:0] bus suffix (SPEC.md Sec 2.11) --
# these netlist as a bare pin name, not `pin[index]`.
SINGLE_BIT_PINS = {
    "ctrl_pfeta_source", "ctrl_pfetb_source",
    "ctrl_nfeta_source", "ctrl_nfetb_source",
    "ctrl_dpp_source", "ctrl_dpn_source",
}

# Resistance of each config tie, in ohms, as SPICE text.
#
# These ties are meant to be dead shorts, and used to be written as a
# literal `0`. ngspice does not accept a zero-ohm resistor: it silently
# substitutes 1e-12 ohms and prints
#
#     Warning: Value of resistor r.x2.rcfg188 is too small, set to 1.000000e-12
#
# once per tie -- 192 warnings before a simulation of a routed design has
# printed anything of its own, which buries any real warning the run
# produces. Writing the substitution ourselves silences
# all 192 and simulates exactly the circuit ngspice was already solving,
# since 1e-12 is the value it was substituting anyway. A config pin is a
# switch gate inside the chip, so no DC current flows through these ties
# and the resistance is electrically irrelevant regardless.
CONFIG_TIE_OHMS = "1e-12"


def render_config_spice(config: SwitchConfig) -> str:
    """Return a SPICE fragment tying every mosbius.sym config pin to
    VGND or VDPWR according to `config`. Include this alongside an
    instance of `mosbius.sym` (named e.g. `x1`) in a testbench.
    """
    lines = [
        "* Generated by mosbius/spice.py -- ties every mosbius.sym config",
        "* pin to VGND (0) or VDPWR (1), per SPEC.md Sec 3.7.",
        "* Requires VDPWR and VGND nets to already exist in the enclosing circuit.",
        f"* Each tie is {CONFIG_TIE_OHMS} ohms, ngspice's own stand-in for the 0 ohms",
        "* meant here -- writing it out avoids one \"resistor is too small\"",
        "* warning per tie.",
    ]
    for bit in range(config.chip.num_bits):
        info = config.chip.all_bits[bit]
        if info.pin in SINGLE_BIT_PINS:
            pin_net = info.pin
        else:
            pin_net = f"{info.pin}[{info.index}]"
        rail = "VDPWR" if bit in config.bits else "VGND"
        lines.append(f"Rcfg{bit} {pin_net} {rail} {CONFIG_TIE_OHMS}")
    return "\n".join(lines) + "\n"


def render_bus_wire_caps(chip: Chip = DEFAULT_CHIP) -> str:
    """Return a SPICE fragment adding real bus-wire self-capacitance (to
    VGND) on all 12 switch-matrix bus rows. Include alongside an instance
    of `mosbius.sym` in a testbench, the same way as `render_config_spice()`
    -- safe to include unconditionally, since a bus row not used by a
    given design just gets one extra, electrically inert capacitor.

    The numbers, and the note on where they came from and which one is an
    estimate, live with the part they were extracted from, in
    mosbius/chips/__init__.py.
    """
    lines = [
        "* Generated by mosbius/spice.py -- real horizontal bus-wire",
        "* self-capacitance to VGND on all 12 switch-matrix bus rows,",
        f"* extracted from {chip.title}'s layout. Requires VGND to",
        "* already exist in the enclosing circuit.",
    ]
    for i, (net, farads) in enumerate(chip.bus_wire_cap.items()):
        lines.append(f"Cwire{i} {net} VGND {farads * 1e15:.2f}f")
    return "\n".join(lines) + "\n"
