# SPDX-License-Identifier: Apache-2.0
"""Emit an ngspice include that drives every `mosbius.sym` config pin
directly, per SPEC.md Sec 3.7.

Because `mosbius.sym` already exposes all 192 config bits as named digital
input pins, simulating a SwitchConfig needs no behavioural model of the
shift register at all -- each bit becomes a short-circuit tie from its pin
net to either VGND (bit clear) or VDPWR (bit set). Ties, not independent
voltage sources, so every config pin rides on the testbench's own
VDPWR/VGND supply nets rather than a second, possibly-mismatched copy of
them.

This is also SPEC.md Sec 3.8's "SPICE subckt" decode output form: the
identical include drives a bitstream decoded from anywhere, not just one
produced by the (not-yet-built) router.
"""

from __future__ import annotations

from mosbius.bitmap import ALL_BITS
from mosbius.model import SwitchConfig, bus_node

# mosbius.sym pins declared without a [N:0] bus suffix (SPEC.md Sec 2.11) --
# these netlist as a bare pin name, not `pin[index]`.
SINGLE_BIT_PINS = {
    "ctrl_pfeta_source", "ctrl_pfetb_source",
    "ctrl_nfeta_source", "ctrl_nfetb_source",
    "ctrl_dpp_source", "ctrl_dpn_source",
}

# Resistance of each config tie, in ohms, as SPICE text.
#
# These ties are meant to be dead shorts, and used to be written as a
# literal `0`. ngspice does not accept a zero-ohm resistor: it silently
# substitutes 1e-12 ohms and prints
#
#     Warning: Value of resistor r.x2.rcfg188 is too small, set to 1.000000e-12
#
# once per tie -- 192 warnings before a simulation of a routed design has
# printed anything of its own, which buries any real warning the run
# produces. Writing the substitution ourselves silences
# all 192 and simulates exactly the circuit ngspice was already solving,
# since 1e-12 is the value it was substituting anyway. A config pin is a
# switch gate inside the chip, so no DC current flows through these ties
# and the resistance is electrically irrelevant regardless.
CONFIG_TIE_OHMS = "1e-12"


def render_config_spice(config: SwitchConfig) -> str:
    """Return a SPICE fragment tying every mosbius.sym config pin to
    VGND or VDPWR according to `config`. Include this alongside an
    instance of `mosbius.sym` (named e.g. `x1`) in a testbench.
    """
    lines = [
        "* Generated by mosbius/spice.py -- ties every mosbius.sym config",
        "* pin to VGND (0) or VDPWR (1), per SPEC.md Sec 3.7.",
        "* Requires VDPWR and VGND nets to already exist in the enclosing circuit.",
        f"* Each tie is {CONFIG_TIE_OHMS} ohms, ngspice's own stand-in for the 0 ohms",
        "* meant here -- writing it out avoids 192 \"resistor is too small\" warnings.",
    ]
    for bit in range(192):
        info = ALL_BITS[bit]
        if info.pin in SINGLE_BIT_PINS:
            pin_net = info.pin
        else:
            pin_net = f"{info.pin}[{info.index}]"
        rail = "VDPWR" if bit in config.bits else "VGND"
        lines.append(f"Rcfg{bit} {pin_net} {rail} {CONFIG_TIE_OHMS}")
    return "\n".join(lines) + "\n"


# Real horizontal bus-wire self-capacitance to substrate, per switch-matrix
# bus row -- the actual physical metal trace running a bus row's full
# length across all 26 columns of the matrix, in farads. This is a genuinely
# different, longer-distance effect than anything device-level: every bus
# row is otherwise a zero-length ideal net in a routed simulation, which
# understates real silicon timing significantly (see TODO.md Sec 1 / the
# ring-oscillator investigation in project memory: including this closed
# real ground, ~93.5MHz -> ~37.62MHz on the measured ring-oscillator
# bitstream vs. its real ~30MHz silicon measurement).
#
# Extracted via magic PEX on ttsky-mini-mosbius/mag/asw_matrix.mag (the
# full matrix, not a single column -- `extract all` + `extresist` +
# `ext2spice cthresh=5f rthresh=10`), then summing every real (non-self)
# capacitor touching each bus row's own resistor-connected wire network.
# Verified independently twice (2026-08-22): 4 of 5 rows measured both
# times agree to within <1%. `bus_B[2]` did NOT -- the first measurement
# (1819.36fF) went through the special `asw_col_short` column assuming its
# per-index row order matches the regular (hardware-validated)
# `asw_col_a`/`asw_col_b` columns' `[6,3,5,2,4,1]` pattern; re-checking
# directly proved that assumption wrong for `asw_col_short` (its supposed
# row-2 node isn't even electrically the same net as the real `bus_B[2]`
# measured through a regular column). The value below (922.84fF) comes
# only from regular columns, using the confirmed mapping. `bus_B[5]`
# couldn't be found as a distinctly-labeled node in either extraction run
# (an ext2spice net-naming quirk specific to that one row/column
# combination, not yet understood) -- using `bus_A[5]`'s value as a
# same-row estimate, flagged here rather than silently guessed.
BUS_WIRE_CAPACITANCE_F: dict[str, float] = {
    bus_node("A", 1): 885.65e-15,
    bus_node("A", 2): 874.79e-15,
    bus_node("A", 3): 864.30e-15,
    bus_node("A", 4): 745.87e-15,
    bus_node("A", 5): 735.37e-15,
    bus_node("A", 6): 724.85e-15,
    bus_node("B", 1): 938.25e-15,
    bus_node("B", 2): 922.84e-15,
    bus_node("B", 3): 901.54e-15,
    bus_node("B", 4): 772.52e-15,
    bus_node("B", 5): 735.37e-15,  # estimated, see note above -- not independently measured
    bus_node("B", 6): 746.72e-15,
}


def render_bus_wire_caps() -> str:
    """Return a SPICE fragment adding real bus-wire self-capacitance (to
    VGND) on all 12 switch-matrix bus rows. Include alongside an instance
    of `mosbius.sym` in a testbench, the same way as `render_config_spice()`
    -- safe to include unconditionally, since a bus row not used by a
    given design just gets one extra, electrically inert capacitor.
    """
    lines = [
        "* Generated by mosbius/spice.py -- real horizontal bus-wire",
        "* self-capacitance to VGND on all 12 switch-matrix bus rows,",
        "* extracted from layout (see BUS_WIRE_CAPACITANCE_F). Requires",
        "* VGND to already exist in the enclosing circuit.",
    ]
    for i, (net, farads) in enumerate(BUS_WIRE_CAPACITANCE_F.items()):
        lines.append(f"Cwire{i} {net} VGND {farads * 1e15:.2f}f")
    return "\n".join(lines) + "\n"
