# SPDX-License-Identifier: Apache-2.0
"""Emit an ngspice include that drives every `mosbius.sym` config pin
directly, per SPEC.md Sec 3.7.

Because `mosbius.sym` already exposes all 192 config bits as named digital
input pins, simulating a SwitchConfig needs no behavioural model of the
shift register at all -- each bit becomes a 0-ohm tie from its pin net to
either VGND (bit clear) or VDPWR (bit set). Ties, not independent voltage
sources, so every config pin rides on the testbench's own VDPWR/VGND
supply nets rather than a second, possibly-mismatched copy of them.

This is also SPEC.md Sec 3.8's "SPICE subckt" decode output form: the
identical include drives a bitstream decoded from anywhere, not just one
produced by the (not-yet-built) router.
"""

from __future__ import annotations

from mosbius.bitmap import ALL_BITS
from mosbius.model import SwitchConfig

# mosbius.sym pins declared without a [N:0] bus suffix (SPEC.md Sec 2.11) --
# these netlist as a bare pin name, not `pin[index]`.
SINGLE_BIT_PINS = {
    "ctrl_pfeta_source", "ctrl_pfetb_source",
    "ctrl_nfeta_source", "ctrl_nfetb_source",
    "ctrl_dpp_source", "ctrl_dpn_source",
}


def render_config_spice(config: SwitchConfig) -> str:
    """Return a SPICE fragment tying every mosbius.sym config pin to
    VGND or VDPWR according to `config`. Include this alongside an
    instance of `mosbius.sym` (named e.g. `x1`) in a testbench.
    """
    lines = [
        "* Generated by mosbius/spice.py -- ties every mosbius.sym config",
        "* pin to VGND (0) or VDPWR (1), per SPEC.md Sec 3.7.",
        "* Requires VDPWR and VGND nets to already exist in the enclosing circuit.",
    ]
    for bit in range(192):
        info = ALL_BITS[bit]
        if info.pin in SINGLE_BIT_PINS:
            pin_net = info.pin
        else:
            pin_net = f"{info.pin}[{info.index}]"
        rail = "VDPWR" if bit in config.bits else "VGND"
        lines.append(f"Rcfg{bit} {pin_net} {rail} 0")
    return "\n".join(lines) + "\n"
