# SPDX-License-Identifier: Apache-2.0
"""Turn a netlist.py-style netlist (the same generic-device text
route.py/tests/test_route.py already use) into a drawable xschem .sch file
built on minimosbius_template.sch's port layout.

Why this exists rather than hand-placing wire coordinates: M2 found that
xschem wire labels only merge net names across genuinely *touching* wire
segments -- a single misplaced coordinate silently produces a floating
pin. schgen.py already has a proven, provably collision-free layout
algorithm (unique jog column per connection, dedicated channel row per
net) for exactly this problem, just aimed at DecodedDesign (post-route,
hardware-role devices) rather than a pre-route MosbiusDesign (generic
devices, user-chosen net names). This script is that same algorithm
retargeted at parse_netlist()'s output, so example schematics are
generated -- and therefore correct by construction -- rather than typed
in by hand.

Usage: python3 tools/gen_example_schematic.py <netlist.spice> <out.sch>
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mosbius.netlist import (
    DEVICE_PINS, IMPLICIT_PINS, PORT_NAMES, SYMBOL_KIND, parse_netlist,
)
from mosbius.schgen import (
    _NMOS_PINS, _NSINK_PINS, _OTA_PINS, _PMOS_PINS, _PSOURCE_PINS,
)

# Reuse schgen's pin coordinates rather than keeping a second copy: they
# have to match xschem/mosbius_lib/*.sym exactly, and one table that is
# wrong is easier to spot than two tables that disagree.
_PINS_BY_KIND = {
    "nmos": _NMOS_PINS, "pmos": _PMOS_PINS,
    "nsink": _NSINK_PINS, "psource": _PSOURCE_PINS,
    "ota": _OTA_PINS,
}
_SYMBOL_BY_KIND = {v: k for k, v in SYMBOL_KIND.items()}

DEVICE_PITCH = 500
JOG_STEP = 8
CHANNEL_BASE_Y = -1200
CHANNEL_PITCH = 60


@dataclass(frozen=True)
class _Connection:
    pin_x: int
    pin_y: int
    net: str
    jog_base_x: int  # see schgen._Connection


def generate(netlist_text: str, title: str) -> str:
    design = parse_netlist(netlist_text)

    lines = [
        "v {xschem version=3.4.8RC file_version=1.2}",
        "G {}",
        "K {}",
        "V {}",
        "S {}",
        "E {}",
        f"T {{{title} -- generated by tools/gen_example_schematic.py from the "
        f"netlist below, do not hand-edit}} -80 -350 0 0 0.25 0.25 {{}}",
    ]

    connections: list[_Connection] = []
    net_connections: dict[str, list[_Connection]] = {}
    component_lines = []

    for i, dev in enumerate(design.devices):
        pins = _PINS_BY_KIND[dev.kind]
        symname = _SYMBOL_BY_KIND[dev.kind]
        origin_x = i * DEVICE_PITCH
        prop_str = " ".join(f"{k}={v}" for k, v in dev.properties.items())
        component_lines.append(
            f"C {{{symname}.sym}} {origin_x} 0 0 0 {{name={dev.name} {prop_str}}}"
        )
        for term, net in dev.terminals.items():
            if term in IMPLICIT_PINS:
                continue  # symbol supplies the body tie; nothing to draw
            dx, dy = pins[term]
            conn = _Connection(
                pin_x=origin_x + dx, pin_y=dy, net=net,
                jog_base_x=origin_x + max(px for px, _ in pins.values()),
            )
            connections.append(conn)
            net_connections.setdefault(net, []).append(conn)

    jog_x_by_conn: dict[int, int] = {}
    channel_y_by_net: dict[str, int] = {}
    counter = 0
    for net_index, (net, conns) in enumerate(sorted(net_connections.items())):
        channel_y_by_net[net] = CHANNEL_BASE_Y - net_index * CHANNEL_PITCH
        for conn in conns:
            jog_x_by_conn[id(conn)] = counter
            counter += 1

    wire_lines = []
    for conn in connections:
        jog_col = jog_x_by_conn[id(conn)]
        jog_x = conn.jog_base_x + JOG_STEP + jog_col
        channel_y = channel_y_by_net[conn.net]
        wire_lines.append(f"N {conn.pin_x} {conn.pin_y} {jog_x} {conn.pin_y} {{\nlab={conn.net}}}")
        wire_lines.append(f"N {jog_x} {conn.pin_y} {jog_x} {channel_y} {{\nlab={conn.net}}}")

    for net, conns in net_connections.items():
        min_x = min(c.jog_base_x + JOG_STEP + jog_x_by_conn[id(c)] for c in conns)
        max_x = max(c.jog_base_x + JOG_STEP + jog_x_by_conn[id(c)] for c in conns)
        channel_y = channel_y_by_net[net]
        if min_x != max_x:
            wire_lines.append(f"N {min_x} {channel_y} {max_x} {channel_y} {{\nlab={net}}}")
        # A net that reaches one of the design's fixed ports gets a fresh
        # iopin.sym placed right at its own channel -- same technique as
        # mosbius/schgen.py, proven in M2: anchoring at that net's own
        # already-disjoint jog-column range means the port can never sit
        # inside another net's channel span.
        if net in PORT_NAMES:
            wire_lines.append(
                f"C {{devices/iopin.sym}} {min_x} {channel_y} 0 1 "
                f"{{name=port_{net} lab={net}}}"
            )

    lines.extend(wire_lines)
    lines.extend(component_lines)
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <netlist.spice> <out.sch>", file=sys.stderr)
        return 2
    netlist_path, out_path = Path(argv[1]), Path(argv[2])
    title = out_path.stem
    Path(out_path).write_text(generate(netlist_path.read_text(), title))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
